name: aegir
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - altgraph=0.17.3=py311h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - click=8.1.7=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - jpeg=9e=h5eee18b_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h77fa898_7
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libgomp=13.2.0=h77fa898_7
  - liblapack=3.9.0=22_linux64_openblas
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.4=py311h64a7726_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_1
  - pillow=10.3.0=py311h5eee18b_0
  - pip=24.0=py311h06a4308_0
  - pyinstaller=5.13.2=py311h5eee18b_0
  - pyinstaller-hooks-contrib=2022.14=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - python-dotenv=0.21.0=py311h06a4308_0
  - python_abi=3.11=2_cp311
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py311h06a4308_0
  - smbus2=0.4.3=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - genicam==1.4.0
      - harvesters==1.4.3
